### ISSUE TITLE
Tuples: Support multiple tuples in Hdict

### ISSUE THREAD

**Issue by polsm91** [bsc-dd/hecuba#249]
The Hdict or the Python Typespec parser do not implement multiple tuples as values for a given key.

**Comment by polsm91** [comment]
```python

class GlobalStats(StorageDict):
    '''
    @TypeSpec dict<<time:int, lat:double, lon:double, ilev:int>, m_cloudfract:tuple<float,float,float,int>, m_humidity:tuple<float,float,float,int>, m_icewater:tuple<float,float,float,int>, m_liquidwate:tuple<float,float,float,int>, m_ozone:tuple<float,float,float,int>, m_pot_vorticit:tuple<float,float,float,int>, m_rain:tuple<float,float,float,int>, m_snow:tuple<float,float,float,int>>
    '''
```


Produces:

```bash
Traceback (most recent call last):
  File "/apps/COMPSs/2.4.rc1903/Bindings/python/2/pycompss/runtime/launch.py", line 386, in <module>
    compss_main()
  File "/apps/COMPSs/2.4.rc1903/Bindings/python/2/pycompss/runtime/launch.py", line 161, in compss_main
    execfile(app_path, globals())  # MAIN EXECUTION
  File "/home/bsc31/bsc31906/EARTH_COMPSs/jesus_tuples_prints.py", line 130, in <module>
    dayStats = GlobalStats('day' + name)
  File "/home/bsc31/bsc31906/.local/lib/python2.7/site-packages/Hecuba-0.1-py2.7-linux-x86_64.egg/hecuba/hdict.py", line 342, in __init__
    self._item_builder = namedtuple('row', key_names + column_names)
  File "/apps/PYTHON/2.7.13/INTEL/lib/python2.7/collections.py", line 364, in namedtuple
    raise ValueError('Encountered duplicate field name: %r' % name)
ValueError: Encountered duplicate field name: 'type'

```
